### ISSUE TITLE
Fix web version search url

### ISSUE THREAD

**Issue by OdysseasKr** [OdysseasKr/UltimateSpotifySearch-Chrome#5]
For the Web version the URL should be changed from
```https://open.spotify.com/search/results/```
to 
```https://open.spotify.com/search/```.

https://github.com/OdysseasKr/UltimateSpotifySearch/commit/95dac29e260338156dd7780fb3be5787cbc28b39#commitcomment-41877984

**Comment by Skibit** [comment]
You're doing great work, thank you for updating!!!!
